theme: minima
author: litjhr
title: Self-Test
email: jhr32272@outlook.com
navigation:
  - title: "首页"
    url: "/skills-github-pages/"
  - title: "文章"
    url: "/skills-github-pages/posts/"
  - title: "litjhr"
    url: "/skills-github-pages/intro/"
