theme: minima
author: litjhr
title: Self-Test
email: jhr32272@outlook.com
navigation:
  - title: "首页"
    url: "/skills-github-pages/"
  - title: "litjhr"
    url: "/skills-github-pages/intro"
  - title: "ano"
    url: "/skills-github-pages/1"
